/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import local.rdps.svja.dao.jooq.tables.GroupPermissions;
import local.rdps.svja.dao.jooq.tables.interfaces.IGroupPermissions;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupPermissionsRecord extends UpdatableRecordImpl<GroupPermissionsRecord> implements Record5<Integer, Integer, Integer, Integer, LocalDateTime>, IGroupPermissions {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>group_permissions.group_id</code>.
     */
    @Override
    public void setGroupId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>group_permissions.group_id</code>.
     */
    @NotNull
    @Override
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>group_permissions.can_write</code>.
     */
    @Override
    public void setCanWrite(@NotNull Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>group_permissions.can_write</code>.
     */
    @NotNull
    @Override
    public Integer getCanWrite() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>group_permissions.can_admin</code>.
     */
    @Override
    public void setCanAdmin(@NotNull Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>group_permissions.can_admin</code>.
     */
    @NotNull
    @Override
    public Integer getCanAdmin() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>group_permissions.modified_by</code>.
     */
    @Override
    public void setModifiedBy(@NotNull Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>group_permissions.modified_by</code>.
     */
    @NotNull
    @Override
    public Integer getModifiedBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>group_permissions.modified_date</code>.
     */
    @Override
    public void setModifiedDate(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>group_permissions.modified_date</code>.
     */
    @Nullable
    @Override
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Integer, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row5<Integer, Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return GroupPermissions.GROUP_PERMISSIONS.GROUP_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field2() {
        return GroupPermissions.GROUP_PERMISSIONS.CAN_WRITE;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return GroupPermissions.GROUP_PERMISSIONS.CAN_ADMIN;
    }

    @Override
    @NotNull
    public Field<Integer> field4() {
        return GroupPermissions.GROUP_PERMISSIONS.MODIFIED_BY;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return GroupPermissions.GROUP_PERMISSIONS.MODIFIED_DATE;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getGroupId();
    }

    @Override
    @NotNull
    public Integer component2() {
        return getCanWrite();
    }

    @Override
    @NotNull
    public Integer component3() {
        return getCanAdmin();
    }

    @Override
    @NotNull
    public Integer component4() {
        return getModifiedBy();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getModifiedDate();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getGroupId();
    }

    @Override
    @NotNull
    public Integer value2() {
        return getCanWrite();
    }

    @Override
    @NotNull
    public Integer value3() {
        return getCanAdmin();
    }

    @Override
    @NotNull
    public Integer value4() {
        return getModifiedBy();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getModifiedDate();
    }

    @Override
    @NotNull
    public GroupPermissionsRecord value1(@NotNull Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    @NotNull
    public GroupPermissionsRecord value2(@NotNull Integer value) {
        setCanWrite(value);
        return this;
    }

    @Override
    @NotNull
    public GroupPermissionsRecord value3(@NotNull Integer value) {
        setCanAdmin(value);
        return this;
    }

    @Override
    @NotNull
    public GroupPermissionsRecord value4(@NotNull Integer value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    @NotNull
    public GroupPermissionsRecord value5(@Nullable LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    @NotNull
    public GroupPermissionsRecord values(@NotNull Integer value1, @NotNull Integer value2, @NotNull Integer value3, @NotNull Integer value4, @Nullable LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGroupPermissions from) {
        setGroupId(from.getGroupId());
        setCanWrite(from.getCanWrite());
        setCanAdmin(from.getCanAdmin());
        setModifiedBy(from.getModifiedBy());
        setModifiedDate(from.getModifiedDate());
    }

    @Override
    public <E extends IGroupPermissions> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupPermissionsRecord
     */
    public GroupPermissionsRecord() {
        super(GroupPermissions.GROUP_PERMISSIONS);
    }

    /**
     * Create a detached, initialised GroupPermissionsRecord
     */
    public GroupPermissionsRecord(@NotNull Integer groupId, @NotNull Integer canWrite, @NotNull Integer canAdmin, @NotNull Integer modifiedBy, @Nullable LocalDateTime modifiedDate) {
        super(GroupPermissions.GROUP_PERMISSIONS);

        setGroupId(groupId);
        setCanWrite(canWrite);
        setCanAdmin(canAdmin);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
    }
}
