/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import local.rdps.svja.dao.jooq.tables.Groups;
import local.rdps.svja.dao.jooq.tables.interfaces.IGroups;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> implements Record5<Integer, String, String, Integer, LocalDateTime>, IGroups {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>groups.id</code>.
     */
    @Override
    public void setId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>groups.id</code>.
     */
    @NotNull
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>groups.name</code>.
     */
    @Override
    public void setName(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>groups.name</code>.
     */
    @NotNull
    @Override
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>groups.description</code>.
     */
    @Override
    public void setDescription(@NotNull String value) {
        set(2, value);
    }

    /**
     * Getter for <code>groups.description</code>.
     */
    @NotNull
    @Override
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>groups.modified_by</code>.
     */
    @Override
    public void setModifiedBy(@NotNull Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>groups.modified_by</code>.
     */
    @NotNull
    @Override
    public Integer getModifiedBy() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>groups.modified_date</code>.
     */
    @Override
    public void setModifiedDate(@Nullable LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>groups.modified_date</code>.
     */
    @Nullable
    @Override
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Integer, String, String, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row5<Integer, String, String, Integer, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Integer> field1() {
        return Groups.GROUPS.ID;
    }

    @Override
    @NotNull
    public Field<String> field2() {
        return Groups.GROUPS.NAME;
    }

    @Override
    @NotNull
    public Field<String> field3() {
        return Groups.GROUPS.DESCRIPTION;
    }

    @Override
    @NotNull
    public Field<Integer> field4() {
        return Groups.GROUPS.MODIFIED_BY;
    }

    @Override
    @NotNull
    public Field<LocalDateTime> field5() {
        return Groups.GROUPS.MODIFIED_DATE;
    }

    @Override
    @NotNull
    public Integer component1() {
        return getId();
    }

    @Override
    @NotNull
    public String component2() {
        return getName();
    }

    @Override
    @NotNull
    public String component3() {
        return getDescription();
    }

    @Override
    @NotNull
    public Integer component4() {
        return getModifiedBy();
    }

    @Override
    @Nullable
    public LocalDateTime component5() {
        return getModifiedDate();
    }

    @Override
    @NotNull
    public Integer value1() {
        return getId();
    }

    @Override
    @NotNull
    public String value2() {
        return getName();
    }

    @Override
    @NotNull
    public String value3() {
        return getDescription();
    }

    @Override
    @NotNull
    public Integer value4() {
        return getModifiedBy();
    }

    @Override
    @Nullable
    public LocalDateTime value5() {
        return getModifiedDate();
    }

    @Override
    @NotNull
    public GroupsRecord value1(@NotNull Integer value) {
        setId(value);
        return this;
    }

    @Override
    @NotNull
    public GroupsRecord value2(@NotNull String value) {
        setName(value);
        return this;
    }

    @Override
    @NotNull
    public GroupsRecord value3(@NotNull String value) {
        setDescription(value);
        return this;
    }

    @Override
    @NotNull
    public GroupsRecord value4(@NotNull Integer value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    @NotNull
    public GroupsRecord value5(@Nullable LocalDateTime value) {
        setModifiedDate(value);
        return this;
    }

    @Override
    @NotNull
    public GroupsRecord values(@NotNull Integer value1, @NotNull String value2, @NotNull String value3, @NotNull Integer value4, @Nullable LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IGroups from) {
        setId(from.getId());
        setName(from.getName());
        setDescription(from.getDescription());
        setModifiedBy(from.getModifiedBy());
        setModifiedDate(from.getModifiedDate());
    }

    @Override
    public <E extends IGroups> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(@NotNull Integer id, @NotNull String name, @NotNull String description, @NotNull Integer modifiedBy, @Nullable LocalDateTime modifiedDate) {
        super(Groups.GROUPS);

        setId(id);
        setName(name);
        setDescription(description);
        setModifiedBy(modifiedBy);
        setModifiedDate(modifiedDate);
    }
}
