/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq;


import javax.annotation.processing.Generated;

import local.rdps.svja.dao.jooq.tables.Files;
import local.rdps.svja.dao.jooq.tables.GroupPermissions;
import local.rdps.svja.dao.jooq.tables.Groups;
import local.rdps.svja.dao.jooq.tables.ProjectFiles;
import local.rdps.svja.dao.jooq.tables.Projects;
import local.rdps.svja.dao.jooq.tables.UserGroups;
import local.rdps.svja.dao.jooq.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FILES_ID_INDEX = Internal.createIndex(DSL.name("files_id_index"), Files.FILES, new OrderField[] { Files.FILES.ID }, false);
    public static final Index GROUP_PERMISSIONS_GID_INDEX = Internal.createIndex(DSL.name("group_permissions_gid_index"), GroupPermissions.GROUP_PERMISSIONS, new OrderField[] { GroupPermissions.GROUP_PERMISSIONS.GROUP_ID }, false);
    public static final Index GROUPS_ID_INDEX = Internal.createIndex(DSL.name("groups_id_index"), Groups.GROUPS, new OrderField[] { Groups.GROUPS.ID }, false);
    public static final Index PROJECT_FILES_FID_INDEX = Internal.createIndex(DSL.name("project_files_fid_index"), ProjectFiles.PROJECT_FILES, new OrderField[] { ProjectFiles.PROJECT_FILES.FILE_ID }, false);
    public static final Index PROJECT_FILES_PID_INDEX = Internal.createIndex(DSL.name("project_files_pid_index"), ProjectFiles.PROJECT_FILES, new OrderField[] { ProjectFiles.PROJECT_FILES.PROJECT_ID }, false);
    public static final Index PROJECTS_ID_INDEX = Internal.createIndex(DSL.name("projects_id_index"), Projects.PROJECTS, new OrderField[] { Projects.PROJECTS.ID }, false);
    public static final Index USER_GROUPS_GID_INDEX = Internal.createIndex(DSL.name("user_groups_gid_index"), UserGroups.USER_GROUPS, new OrderField[] { UserGroups.USER_GROUPS.GROUP_ID }, false);
    public static final Index USER_GROUPS_UID_INDEX = Internal.createIndex(DSL.name("user_groups_uid_index"), UserGroups.USER_GROUPS, new OrderField[] { UserGroups.USER_GROUPS.USER_ID }, false);
    public static final Index USERS_ID_INDEX = Internal.createIndex(DSL.name("users_id_index"), Users.USERS, new OrderField[] { Users.USERS.ID }, false);
}
