/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import local.rdps.svja.dao.jooq.DefaultSchema;
import local.rdps.svja.dao.jooq.Indexes;
import local.rdps.svja.dao.jooq.Keys;
import local.rdps.svja.dao.jooq.tables.records.GroupPermissionsRecord;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupPermissions extends TableImpl<GroupPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>group_permissions</code>
     */
    public static final GroupPermissions GROUP_PERMISSIONS = new GroupPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GroupPermissionsRecord> getRecordType() {
        return GroupPermissionsRecord.class;
    }

    /**
     * The column <code>group_permissions.group_id</code>.
     */
    public final TableField<GroupPermissionsRecord, Integer> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>group_permissions.can_write</code>.
     */
    public final TableField<GroupPermissionsRecord, Integer> CAN_WRITE = createField(DSL.name("can_write"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>group_permissions.can_admin</code>.
     */
    public final TableField<GroupPermissionsRecord, Integer> CAN_ADMIN = createField(DSL.name("can_admin"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>group_permissions.modified_by</code>.
     */
    public final TableField<GroupPermissionsRecord, Integer> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>group_permissions.modified_date</code>.
     */
    public final TableField<GroupPermissionsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private GroupPermissions(Name alias, Table<GroupPermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private GroupPermissions(Name alias, Table<GroupPermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>group_permissions</code> table reference
     */
    public GroupPermissions(String alias) {
        this(DSL.name(alias), GROUP_PERMISSIONS);
    }

    /**
     * Create an aliased <code>group_permissions</code> table reference
     */
    public GroupPermissions(Name alias) {
        this(alias, GROUP_PERMISSIONS);
    }

    /**
     * Create a <code>group_permissions</code> table reference
     */
    public GroupPermissions() {
        this(DSL.name("group_permissions"), null);
    }

    public <O extends Record> GroupPermissions(Table<O> child, ForeignKey<O, GroupPermissionsRecord> key) {
        super(child, key, GROUP_PERMISSIONS);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GROUP_PERMISSIONS_GID_INDEX);
    }

    @Override
    @NotNull
    public UniqueKey<GroupPermissionsRecord> getPrimaryKey() {
        return Keys.PK_GROUP_PERMISSIONS;
    }

    @Override
    @NotNull
    public List<UniqueKey<GroupPermissionsRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupPermissionsRecord>>asList(Keys.PK_GROUP_PERMISSIONS);
    }

    @Override
    @NotNull
    public List<ForeignKey<GroupPermissionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GroupPermissionsRecord, ?>>asList(Keys.FK_GROUP_PERMISSIONS_GROUPS_1, Keys.FK_GROUP_PERMISSIONS_USERS_1);
    }

    private transient Groups _groups;
    private transient Users _users;

    public Groups groups() {
        if (_groups == null)
            _groups = new Groups(this, Keys.FK_GROUP_PERMISSIONS_GROUPS_1);

        return _groups;
    }

    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.FK_GROUP_PERMISSIONS_USERS_1);

        return _users;
    }

    @Override
    @NotNull
    public GroupPermissions as(String alias) {
        return new GroupPermissions(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GroupPermissions as(Name alias) {
        return new GroupPermissions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GroupPermissions rename(String name) {
        return new GroupPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GroupPermissions rename(Name name) {
        return new GroupPermissions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row5<Integer, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
