/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import local.rdps.svja.dao.jooq.DefaultSchema;
import local.rdps.svja.dao.jooq.Indexes;
import local.rdps.svja.dao.jooq.Keys;
import local.rdps.svja.dao.jooq.tables.records.UserGroupsRecord;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroups extends TableImpl<UserGroupsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_groups</code>
     */
    public static final UserGroups USER_GROUPS = new UserGroups();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<UserGroupsRecord> getRecordType() {
        return UserGroupsRecord.class;
    }

    /**
     * The column <code>user_groups.user_id</code>.
     */
    public final TableField<UserGroupsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>user_groups.group_id</code>.
     */
    public final TableField<UserGroupsRecord, Integer> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>user_groups.modified_by</code>.
     */
    public final TableField<UserGroupsRecord, Integer> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>user_groups.modified_date</code>.
     */
    public final TableField<UserGroupsRecord, LocalDateTime> MODIFIED_DATE = createField(DSL.name("modified_date"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private UserGroups(Name alias, Table<UserGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserGroups(Name alias, Table<UserGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>user_groups</code> table reference
     */
    public UserGroups(String alias) {
        this(DSL.name(alias), USER_GROUPS);
    }

    /**
     * Create an aliased <code>user_groups</code> table reference
     */
    public UserGroups(Name alias) {
        this(alias, USER_GROUPS);
    }

    /**
     * Create a <code>user_groups</code> table reference
     */
    public UserGroups() {
        this(DSL.name("user_groups"), null);
    }

    public <O extends Record> UserGroups(Table<O> child, ForeignKey<O, UserGroupsRecord> key) {
        super(child, key, USER_GROUPS);
    }

    @Override
    @NotNull
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_GROUPS_GID_INDEX, Indexes.USER_GROUPS_UID_INDEX);
    }

    @Override
    @NotNull
    public UniqueKey<UserGroupsRecord> getPrimaryKey() {
        return Keys.PK_USER_GROUPS;
    }

    @Override
    @NotNull
    public List<UniqueKey<UserGroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<UserGroupsRecord>>asList(Keys.PK_USER_GROUPS);
    }

    @Override
    @NotNull
    public List<ForeignKey<UserGroupsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserGroupsRecord, ?>>asList(Keys.FK_USER_GROUPS_USERS_2, Keys.FK_USER_GROUPS_GROUPS_1, Keys.FK_USER_GROUPS_USERS_1);
    }

    private transient Users _fkUserGroupsUsers_2;
    private transient Groups _groups;
    private transient Users _fkUserGroupsUsers_1;

    public Users fkUserGroupsUsers_2() {
        if (_fkUserGroupsUsers_2 == null)
            _fkUserGroupsUsers_2 = new Users(this, Keys.FK_USER_GROUPS_USERS_2);

        return _fkUserGroupsUsers_2;
    }

    public Groups groups() {
        if (_groups == null)
            _groups = new Groups(this, Keys.FK_USER_GROUPS_GROUPS_1);

        return _groups;
    }

    public Users fkUserGroupsUsers_1() {
        if (_fkUserGroupsUsers_1 == null)
            _fkUserGroupsUsers_1 = new Users(this, Keys.FK_USER_GROUPS_USERS_1);

        return _fkUserGroupsUsers_1;
    }

    @Override
    @NotNull
    public UserGroups as(String alias) {
        return new UserGroups(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public UserGroups as(Name alias) {
        return new UserGroups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UserGroups rename(String name) {
        return new UserGroups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public UserGroups rename(Name name) {
        return new UserGroups(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row4<Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
