/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IFiles extends Serializable {

    /**
     * Setter for <code>files.id</code>.
     */
    public void setId(@NotNull Integer value);

    /**
     * Getter for <code>files.id</code>.
     */
    @NotNull
    public Integer getId();

    /**
     * Setter for <code>files.file_name</code>.
     */
    public void setFileName(@NotNull String value);

    /**
     * Getter for <code>files.file_name</code>.
     */
    @NotNull
    public String getFileName();

    /**
     * Setter for <code>files.description</code>.
     */
    public void setDescription(@Nullable String value);

    /**
     * Getter for <code>files.description</code>.
     */
    @Nullable
    public String getDescription();

    /**
     * Setter for <code>files.modified_by</code>.
     */
    public void setModifiedBy(@NotNull Integer value);

    /**
     * Getter for <code>files.modified_by</code>.
     */
    @NotNull
    public Integer getModifiedBy();

    /**
     * Setter for <code>files.modified_date</code>.
     */
    public void setModifiedDate(@Nullable LocalDateTime value);

    /**
     * Getter for <code>files.modified_date</code>.
     */
    @Nullable
    public LocalDateTime getModifiedDate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IFiles
     */
    public void from(IFiles from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IFiles
     */
    public <E extends IFiles> E into(E into);
}
