/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProjects extends Serializable {

    /**
     * Setter for <code>projects.id</code>.
     */
    public void setId(@NotNull Integer value);

    /**
     * Getter for <code>projects.id</code>.
     */
    @NotNull
    public Integer getId();

    /**
     * Setter for <code>projects.title</code>.
     */
    public void setTitle(@NotNull String value);

    /**
     * Getter for <code>projects.title</code>.
     */
    @NotNull
    public String getTitle();

    /**
     * Setter for <code>projects.description</code>.
     */
    public void setDescription(@Nullable String value);

    /**
     * Getter for <code>projects.description</code>.
     */
    @Nullable
    public String getDescription();

    /**
     * Setter for <code>projects.modified_by</code>.
     */
    public void setModifiedBy(@NotNull Integer value);

    /**
     * Getter for <code>projects.modified_by</code>.
     */
    @NotNull
    public Integer getModifiedBy();

    /**
     * Setter for <code>projects.modified_date</code>.
     */
    public void setModifiedDate(@Nullable LocalDateTime value);

    /**
     * Getter for <code>projects.modified_date</code>.
     */
    @Nullable
    public LocalDateTime getModifiedDate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IProjects
     */
    public void from(IProjects from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IProjects
     */
    public <E extends IProjects> E into(E into);
}
