/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IProjectFiles extends Serializable {

    /**
     * Setter for <code>project_files.project_id</code>.
     */
    public void setProjectId(@NotNull Integer value);

    /**
     * Getter for <code>project_files.project_id</code>.
     */
    @NotNull
    public Integer getProjectId();

    /**
     * Setter for <code>project_files.file_id</code>.
     */
    public void setFileId(@NotNull Integer value);

    /**
     * Getter for <code>project_files.file_id</code>.
     */
    @NotNull
    public Integer getFileId();

    /**
     * Setter for <code>project_files.modified_by</code>.
     */
    public void setModifiedBy(@NotNull Integer value);

    /**
     * Getter for <code>project_files.modified_by</code>.
     */
    @NotNull
    public Integer getModifiedBy();

    /**
     * Setter for <code>project_files.modified_date</code>.
     */
    public void setModifiedDate(@Nullable LocalDateTime value);

    /**
     * Getter for <code>project_files.modified_date</code>.
     */
    @Nullable
    public LocalDateTime getModifiedDate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IProjectFiles
     */
    public void from(IProjectFiles from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IProjectFiles
     */
    public <E extends IProjectFiles> E into(E into);
}
