/*
 * This file is generated by jOOQ.
 */
package local.rdps.svja.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserGroups extends Serializable {

    /**
     * Setter for <code>user_groups.user_id</code>.
     */
    public void setUserId(@NotNull Integer value);

    /**
     * Getter for <code>user_groups.user_id</code>.
     */
    @NotNull
    public Integer getUserId();

    /**
     * Setter for <code>user_groups.group_id</code>.
     */
    public void setGroupId(@NotNull Integer value);

    /**
     * Getter for <code>user_groups.group_id</code>.
     */
    @NotNull
    public Integer getGroupId();

    /**
     * Setter for <code>user_groups.modified_by</code>.
     */
    public void setModifiedBy(@NotNull Integer value);

    /**
     * Getter for <code>user_groups.modified_by</code>.
     */
    @NotNull
    public Integer getModifiedBy();

    /**
     * Setter for <code>user_groups.modified_date</code>.
     */
    public void setModifiedDate(@Nullable LocalDateTime value);

    /**
     * Getter for <code>user_groups.modified_date</code>.
     */
    @Nullable
    public LocalDateTime getModifiedDate();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserGroups
     */
    public void from(IUserGroups from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserGroups
     */
    public <E extends IUserGroups> E into(E into);
}
